apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - image: "registryxcw9261.azurecr.io/tripinsights/poi:v1"
          imagePullPolicy: Always
          name: poi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SQL_SERVER
              value: "sqlserverxcw9261.database.windows.net"
            - name: SQL_DATABASE
              value: "mydrivingDB"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sql-username
                  key: username
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "username"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-password
                  key: password
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "password"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  type: LoadBalancer
  clusterIP: 10.100.2.238
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
  labels:
    deploy: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - image: "registryxcw9261.azurecr.io/tripinsights/trips:1.0"
          imagePullPolicy: Always
          name: trips
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SQL_SERVER
              value: "sqlserverxcw9261.database.windows.net"
            - name: SQL_DATABASE
              value: "mydrivingDB"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sql-username
                  key: username
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "username"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-password
                  key: password
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "password"
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  type: LoadBalancer
  clusterIP: 10.100.2.240
  selector:
    app: trips
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
  labels:
    deploy: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - image: "registryxcw9261.azurecr.io/tripinsights/userprofile:1.0"
          imagePullPolicy: Always
          name: userprofile
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SQL_SERVER
              value: "sqlserverxcw9261.database.windows.net"
            - name: SQL_DATABASE
              value: "mydrivingDB"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sql-username
                  key: username
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "username"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-password
                  key: password
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "password"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  type: LoadBalancer
  clusterIP: 10.100.2.239
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
  labels:
    deploy: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
        - image: "registryxcw9261.azurecr.io/tripinsights/user-java:1.0"
          imagePullPolicy: Always
          name: user-java
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SQL_SERVER
              value: "sqlserverxcw9261.database.windows.net"
            - name: SQL_DATABASE
              value: "mydrivingDB"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sql-username
                  key: username
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "username"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-password
                  key: password
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "password"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  type: LoadBalancer
  clusterIP: 10.100.2.137
  selector:
    app: user-java
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
