# This file contains the essential configs for the ingress controller helm chart

# Verbosity level of the App Gateway Ingress Controller
verbosityLevel: 3

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
  subscriptionId: 401ef870-009b-4f75-9938-f7b20a5a3636
  resourceGroup: teamResources
  name: ingress_gateway

  # Setting appgw.shared to "true" will create an AzureIngressProhibitedTarget CRD.
  # This prohibits AGIC from applying config for any host/path.
  # Use "kubectl get AzureIngressProhibitedTargets" to view and change this.
  shared: false

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
# Leaving this variable out or setting it to blank or empty string would
# result in Ingress Controller observing all acessible namespaces.
#
# kubernetes:
#   watchNamespace: <namespace>

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
armAuth:
  type: aadPodIdentity
  identityResourceID: /subscriptions/401ef870-009b-4f75-9938-f7b20a5a3636/resourcegroups/teamResources/providers/Microsoft.ManagedIdentity/userAssignedIdentities/pod-identity
  identityClientID: 4048d67d-0d4b-4a2d-9ba7-efd63d52573e

## Alternatively you can use Service Principal credentials
# armAuth:
#    type: servicePrincipal
#    secretJSON: <<Generate this value with: "az ad sp create-for-rbac --subscription <subscription-uuid> --role Contributor --sdk-auth | base64 -w0" >>

################################################################################
# Specify if the cluster is Kubernetes RBAC enabled or not
rbac:
  enabled: false # true/false

# Specify aks cluster related information. THIS IS BEING DEPRECATED.
aksClusterConfiguration:
  apiServerAddress: <aks-api-server-address>
