apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              service:
                name: tripviewer
                namespace: web
                port:
                  number: 80
            pathType: Exact
          - path: /api/poi
            backend:
              service:
                name: poi
                namespace: api
                port:
                  number: 80
            pathType: Prefix
          - path: /api/trips
            backend:
              service:
                name: trips
                namespace: api
                port:
                  number: 80
            pathType: Prefix
          - path: /api/user-java
            backend:
              service:
                name: user-java
                namespace: api
                port:
                  number: 80
            pathType: Prefix
          - path: /api/userprofile
            backend:
              service:
                name: userprofile
                namespace: api
                port:
                  number: 80
            pathType: Prefix
