apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  labels:
    deploy: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - image: "registryxcw9261.azurecr.io/tripinsights/userprofile:1.0"
          imagePullPolicy: Always
          name: userprofile
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SQL_SERVER
              value: "sqlserverxcw9261.database.windows.net"
            - name: SQL_DATABASE
              value: "mydrivingDB"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sql-username
                  key: username
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "username"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-password
                  key: password
                  optional:
                    false # same as default; "mysecret" must exist
                    # and include a key named "password"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  type: LoadBalancer
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
